### ISSUE TITLE
1B: Read HV current and voltage

### ISSUE THREAD

**Issue by kkramer215** [sfuphantom/bms-fw#51]
Make sure the current running through the HV board is within range and if not, shutdown signal is sent to the VCU. Further explanations can be found in each test case

**Comment by rafguevara14** [comment]
Power is blocked for testing by this. The HV current needs to be ported but the code works. HV Voltage needs a closer look to see what's wrong

**Comment by kkramer215** [comment]
Update Jan 13, 2024:

- Current monitor on power distribution board. Xander has someone on this. If it doesn't work, gets put on HV board.
- Voltage is from batteries and going into BMS and current is feeding rest of electronics in car. One is SPI and other is I2C. 
- Relevant documentation: https://docs.google.com/document/d/1esFE5GP6mMhir25OIkqpIV73n1zVi_AXTnWvTNE4k4s/edit, https://docs.google.com/document/d/1RWDjLN3mG_uUaCT27qOGboXVOiiY9b4wyCDBaztaTvM/edit
- Current transducer in the lab and voltage transducer is on the high voltage board but can't use it. So start with current transducer. Current transducer may not be placed on a board and instead be seperate. Can plug it into BMS ADC.
- Current transducer placed between inverter and battery but before HV board.

**Comment by danrobren** [comment]
HV current measurement driver tested using launchpad. The behaviour of output_current and flag variables in CCS was consistent with the original documentation. Voltages applied to the ADC pin were not precise since an Arduino Uno was used as a power supply. 
[Original HV current reading driver](https://docs.google.com/document/d/1esFE5GP6mMhir25OIkqpIV73n1zVi_AXTnWvTNE4k4s/edit?usp=sharing)
[Most recent testing documentation]
(https://docs.google.com/document/d/1dXNtHDdUZSdO_01eTJnP-ybrFcNSfhGZ1tWq9ChLQIw/edit?usp=sharing)

**Comment by danrobren** [comment]
- HV current driver code integrated into BMS_master
- Code compiles, links, and flashes correctly
- Infinite loop encountered when running current reading test described in the document above
- Infinite loop at line 396 of sci.c

while ((sci->FLR & (uint32)SCI_TX_INT) == 0U)

- while loop checks whether transmit buffer is ready; it's stuck because transmit buffer is full
- TX buffer remaining full because it is not being emptied/read from

**Comment by danrobren** [comment]
- Fixed the infinite loop issue described above
- Watch expressions set up to read values as shown in testing document; values reading correctly
- sensor_voltage consistently reads higher than lab multimeter and power supply read on ADC pin; zero volts reads correctly, but gap between multimeter and ADC voltage widens as voltage increases. 
- ADC reads maximum when 3.3 volts applied to pin

**Comment by danrobren** [comment]
- Have not yet found a **SAFE** way to run 10+ amps of unidirectional current through the current transducer for testing
- ADC input voltage range was found to be 0V - 3.3V and not 0V - 5V like [Original HV current reading driver](https://docs.google.com/document/d/1esFE5GP6mMhir25OIkqpIV73n1zVi_AXTnWvTNE4k4s/edit?usp=sharing) said
- There is no way to change the ADC input voltage range to 0V - 5V without modifying hardware. 
![image](https://github.com/sfuphantom/bms-fw/assets/109193939/4b11a60d-3204-4c3b-8daa-b455ebc20f8c)
- Either R3 must be desoldered and a new resistor soldered to R4 or R2 desoldered and ADREFHI connected directly to 5V
- ADREFHI should be connected to 5V in the BMS master PCB (if that doesn't cause any other conflicts with other sensors that read out 0V - 3.3V)
- If conflicts do arise, a voltage divider could be used at the OUT pin of the current transducer to scale the output down to 0V - 3.3V
